image: fedora:29
build:
  coverage: '/^\s*Total:\|(\d+\.\d+\%)\s+.*$/'
  script:
    - dnf install -y lcov gcc openssl-devel make
    - make -j world
    - make run-lcov || ":"
    - lcov --list dhcpd-pd.lcov.info || ":"
