language: c

env:
  global:
   - secure: "LfBBhmxEAOVWnKihYpW3DCL/3jiarg3K5e5DVLKfIQ2BGKcAKeGL2Egdm9YqE+YC5oP/gsajKT2QxHGojb1n3dExEvTgXZw8S4i2zkuawB4FYvgseUoE5rPDVqkJZqieJFTWJ8tbQCm0VrLme1e22bkhN3PMH9BelPB7CLOr7aSJZpxC790wskT3bB3IjN+GWZt3xvCLmHG0Qp52HEgZ1HwTl2UPuQovcgqfSpRk6U8wJh/QoLIDnmfxx6zP4JdNCyvRBoeA/UPTE8yW/qrUr5B2y1/7/0l+b2D01rWrreaHffIPSXnIdBJnkhk2/Fh6ScjrarAKgy4EORFun2dEEc+rhIQe1l7yo4564wDRDwww5e4JSMqS6Xt1VkeeUKQmmUatKuU2hL9f7FumIWFzss2vMhhA35f8XcvGVkMlNtFM6gcl/R38ZIcQs5bxzzRT/nt54N6n1hAniOS1avWXViP/NC3CWEkZ8DzXucZRZH7vuV4NPy/2odScILJ8553jriZ3eX5MOJvSGF8Zxv8vhDWIxTQI0h+lDDvpvHTwFevWj2obSlWgslbP4ghVxEMj+gKbeV9zuaQthhb9UWqkk6C3pWWhONy1pHB+KvqiTmM6SBYddYGYjZCar8MeNkY5dgDtea4v6BjxIQTr9m4YKJXJ1yUKPifbRaQ2PyGJfsc="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ensc/dhcpd-pd"
      description: "Build submitted via Travis CI"
    notification_email: github@ensc.de
    build_command_prepend: "true"
    build_command: "make HAVE_NO_GETRANDOM=1 -j all CFLAGS_flto= LDFLAGS_lfto="
    branch_pattern: coverity

dist: xenial
script:
- make HAVE_NO_GETRANDOM=1 -j all CFLAGS_flto= LDFLAGS_lfto=
- make HAVE_NO_GETRANDOM=1 run-gcov || ":"
