language: c

env:
  global:
   - secure: "XpQ08Wp4HrVmkU59z978hrIa1OAbECLmt+B9/MMkY87AXJD2DqCNlQYTBuysuEBKr5P74kMlTph8tGPZ7O4g7vmF+jF7WLibk4sxk+p3BIpIxNGphXwVC9pkcem30bZPa1cx9S1Be4tHjtW9eZPfME8fSXJD0wWpyfb2lUwOP/Mwbtt+Rv9+H0rL7cmAQi6H19hRI+XWp6IcDDQkDSMQQpUUlZHhAY4XrhWC2Dt9n+e/wkOjGZ6iS452WIMEoJbXFnjfbSQsnwA5KNR8EFkhBmj7wwvd/l8bsW8atkuv7L9qJzEsWvRCZFEjPRrSAiqPXq8Fh+H1HVHiixV7ewTTir2i4dgQAStnHgiYJo/lDwrUttLcE1W9peJm/TUpiRtLs0xa6mRFGlSXm3Ezu4yJLTYP6kKvHavn4hJtMQQ8KgL6e9z4OU2bzBwZRbnoGf0+6tu58meSGKIe8xyjFoyE+Wk4V2nhnzzHpyzhKdxaZGBtwKimCJ+VEYeIK7A+hPnLU4+eA/31JObRiinYDVBNnHfhVR1hmGPys1cbL2DBlYBQGmmwJtdGMg3rlkYN7KDABaUM5fTDRwftJidz+ZbC3jR5WMYQHRF+wE8sWVeRd3tMsBQzO6Ay5qEdkqgCzo6sPGYrY3wlk+Mer2IAjyTvG4X5dbWpU0QGdI5/QlZWy/U="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ensc/dhcpd-pd"
      description: "Build submitted via Travis CI"
    notification_email: github@ensc.de
    build_command_prepend: "true"
    branch_pattern: coverity

dist: xenial
script:
- make HAVE_NO_GETRANDOM=1 -j all CFLAGS_flto= LDFLAGS_lfto=
- make HAVE_NO_GETRANDOM=1 run-lcov || ":"
